openapi: 3.0.3
info:
  title: mod DCB FOLIO API
  description: mod DCB FOLIO API
  version: 1.0.0
paths:
  /transactions/{dcbTransactionId}:
    description: DCB Circulation Transaction endpoint
    post:
      description: Create circulation request
      operationId: createCirculationRequest
      tags:
        - circulation
      parameters:
        - $ref: '#/components/parameters/dcbTransactionId'
      requestBody:
        $ref: "#/components/requestBodies/DCBTransaction"
      responses:
        '201':
          $ref: '#/components/responses/TransactionStatusResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /transactions/{dcbTransactionId}/status:
    parameters:
      - $ref: '#/components/parameters/dcbTransactionId'
    get:
      description: Get transaction status across circulation institutions
      operationId: getTransactionStatusById
      tags:
        - circulation
      responses:
        '200':
          $ref: '#/components/responses/TransactionStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      description: Update transaction status across circulation institutions
      operationId: updateTransactionStatus
      tags:
        - circulation
      requestBody:
        $ref: '#/components/requestBodies/TransactionStatusBody'
      responses:
        '200':
          $ref: '#/components/responses/TransactionStatusResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /transactions/status:
    parameters:
      - $ref: '#/components/parameters/fromDate'
      - $ref: '#/components/parameters/toDate'
      - $ref: '#/components/parameters/pageNumber'
      - $ref: '#/components/parameters/pageSize'
    get:
      description: Get a list of updated transactions between from date and to date with optional filtering and pagination
      operationId: getTransactionStatusList
      tags:
        - circulation
      responses:
        '200':
          $ref: '#/components/responses/TransactionStatusResponseCollection'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  requestBodies:
    TransactionStatusBody:
      description: TransactionStatus object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatus.yaml#/TransactionStatus"
    DCBTransaction:
      description: DCB transaction object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/dcbTransaction.yaml#/DcbTransaction"
  responses:
    TransactionStatus:
      description: Transaction Status object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatus.yaml#/TransactionStatus"
    TransactionStatusResponse:
      description: TransactionStatusResponse object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatusResponse.yaml#/TransactionStatusResponse"
    TransactionStatusResponseCollection:
      description: List of TransactionResponse object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatusResponse.yaml#/TransactionStatusResponseCollection"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    dcbTransactionId:
      in: path
      name: dcbTransactionId
      schema:
        type: string
      required: true
    fromDate:
      in: query
      name: fromDate
      description: Start date for filtering transactions
      schema:
        type: string
        format: date-time
      required: true
    toDate:
      in: query
      name: toDate
      description: End date for filtering transactions
      schema:
        type: string
        format: date-time
      required: true
    pageNumber:
      in: query
      name: pageNumber
      description: Page number for pagination (optional)
      schema:
        type: integer
        default: 0
        minimum: 0
        maximum: 2147483647
      required: false
    pageSize:
      in: query
      name: pageSize
      description: Number of items per page (optional)
      schema:
        type: integer
        default: 1000
        minimum: 1
        maximum: 2147483647
      required: false
  schemas:
    InventoryItem:
      $ref: 'schemas/InventoryItem.yaml#/InventoryItem'
    InventoryHolding:
      $ref: 'schemas/InventoryHolding.yaml#/InventoryHolding'
    UserGroupCollection:
      $ref: 'schemas/UserGroup.yaml#/UserGroupCollection'
    UserCollection:
      $ref: 'schemas/User.yaml#/UserCollection'
    CirculationRequest:
      $ref: 'schemas/CirculationRequest.yaml#/CirculationRequest'
    CheckInRequest:
      $ref: 'schemas/CheckInRequest.yaml#/CheckInRequest'
    CheckOutRequest:
      $ref: 'schemas/checkOutRequest.yaml#/CheckOutRequest'
    ServicePointRequest:
      $ref: 'schemas/ServicePointRequest.yaml#/ServicePointRequest'
    CirculationItemCollection:
      $ref: 'schemas/CirculationItem.yaml#/CirculationItemCollection'
    MaterialTypeCollection:
      $ref: 'schemas/MaterialType.yaml#/MaterialTypeCollection'
